title: Fran's Notes
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://francesco-puppo.github.io/notes

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

# plugins:
# - jekyll-target-blank